"""Strategy Runtime (SRT) public contracts."""

from .errors import (
    RuntimeCompatibilityError,
    RuntimeContractError,
    RuntimeExecutionError,
    StrategyRuntimeError,
)
from .contracts import (
    DecisionPoint,
    DecisionWindow,
    ExecutionCapabilities,
    ExecutionOutcome,
    ExecutionPlan,
    ExecutionState,
    OrderSide,
    OrderType,
    PlanLeg,
    PlannedOrder,
    PortfolioSnapshot,
    PriceReference,
    StrategyIdentity,
    WindowExecutor,
)
from .data import (
    DataPreparationRequest,
    PreparedStrategyData,
    PublishedDataSource,
    StrategyDataSource,
)
from .loader import StrategyLoader
from .execution_rules import effective_target_order_type
from .historical_publication import publish_history
from .models import (
    AccountSnapshot,
    CalculationRequest,
    ChannelCapabilities,
    CutoffRule,
    DecisionContract,
    DeploymentSpec,
    ExecutionInstruction,
    ExecutionPolicy,
    ExecutionPricingData,
    ExecutionReceipt,
    ExecutionRequest,
    ImplementationRef,
    HistoryPolicy,
    InputContract,
    InputRequirement,
    MonitoringPolicy,
    ParameterSet,
    PublicationStatus,
    PublishedStrategyData,
    RequiredCapabilities,
    RuntimeDefinition,
    RuntimeRunResult,
    RuntimeRunStatus,
    ReferencePriceSnapshot,
    StrategyDecision,
    StrategyCandidate,
    StrategyExplanation,
    StrategyRelease,
    StrategyRuntimeContext,
    StrategyStateSnapshot,
    canonical_sha256,
)
from .protocols import ExecutableStrategy, ExecutionChannel, RuntimeAccount, RuntimeClock
from .runner import StrategyRunner
from .runtime import StrategyInit, StrategyRuntime
from .strategy import StrategyInstance
from .publication_store import (
    load_strategy_runtime_context,
    publication_manifest_name,
    read_publication,
    write_publication,
)

__version__ = "0.1.0"

__all__ = [
    "AccountSnapshot",
    "CalculationRequest",
    "ChannelCapabilities",
    "CutoffRule",
    "DecisionContract",
    "DeploymentSpec",
    "ExecutableStrategy",
    "ExecutionChannel",
    "ExecutionPolicy",
    "ExecutionInstruction",
    "ExecutionPricingData",
    "ExecutionReceipt",
    "ExecutionRequest",
    "ImplementationRef",
    "HistoryPolicy",
    "InputContract",
    "InputRequirement",
    "MonitoringPolicy",
    "ParameterSet",
    "PublicationStatus",
    "PublishedStrategyData",
    "RequiredCapabilities",
    "RuntimeAccount",
    "RuntimeClock",
    "RuntimeCompatibilityError",
    "RuntimeContractError",
    "RuntimeDefinition",
    "RuntimeRunResult",
    "RuntimeRunStatus",
    "ReferencePriceSnapshot",
    "RuntimeExecutionError",
    "StrategyDecision",
    "StrategyCandidate",
    "StrategyExplanation",
    "StrategyLoader",
    "StrategyRelease",
    "StrategyRuntimeContext",
    "StrategyRuntimeError",
    "StrategyRunner",
    "publication_manifest_name",
    "load_strategy_runtime_context",
    "read_publication",
    "write_publication",
    "StrategyStateSnapshot",
    "canonical_sha256",
    "DataPreparationRequest",
    "DecisionPoint",
    "DecisionWindow",
    "ExecutionCapabilities",
    "ExecutionOutcome",
    "ExecutionPlan",
    "ExecutionState",
    "OrderSide",
    "OrderType",
    "PlanLeg",
    "PlannedOrder",
    "PortfolioSnapshot",
    "PreparedStrategyData",
    "PriceReference",
    "PublishedDataSource",
    "StrategyDataSource",
    "StrategyIdentity",
    "StrategyInit",
    "StrategyInstance",
    "StrategyRuntime",
    "WindowExecutor",
    "effective_target_order_type",
    "publish_history",
]
