"""Strategy Runtime (SRT) public contracts."""

from .backtest_channel import BacktestChannel, BacktestExecutionModel
from .errors import (
    RuntimeCompatibilityError,
    RuntimeContractError,
    RuntimeExecutionError,
    StrategyRuntimeError,
)
from .models import (
    AccountSnapshot,
    CalculationRequest,
    ChannelCapabilities,
    CutoffRule,
    DecisionContract,
    DeploymentSpec,
    ExecutionPolicy,
    ExecutionReceipt,
    ExecutionRequest,
    ImplementationRef,
    InputContract,
    InputRequirement,
    MonitoringPolicy,
    ParameterSet,
    PublicationStatus,
    PublishedStrategyData,
    RequiredCapabilities,
    RuntimeDefinition,
    RuntimeRunResult,
    RuntimeRunStatus,
    StrategyDecision,
    StrategyExplanation,
    StrategyStateSnapshot,
    canonical_sha256,
)
from .protocols import ExecutableStrategy, ExecutionChannel, RuntimeAccount, RuntimeClock
from .runner import StrategyRunner

__version__ = "0.1.0"

__all__ = [
    "AccountSnapshot",
    "BacktestChannel",
    "BacktestExecutionModel",
    "CalculationRequest",
    "ChannelCapabilities",
    "CutoffRule",
    "DecisionContract",
    "DeploymentSpec",
    "ExecutableStrategy",
    "ExecutionChannel",
    "ExecutionPolicy",
    "ExecutionReceipt",
    "ExecutionRequest",
    "ImplementationRef",
    "InputContract",
    "InputRequirement",
    "MonitoringPolicy",
    "ParameterSet",
    "PublicationStatus",
    "PublishedStrategyData",
    "RequiredCapabilities",
    "RuntimeAccount",
    "RuntimeClock",
    "RuntimeCompatibilityError",
    "RuntimeContractError",
    "RuntimeDefinition",
    "RuntimeRunResult",
    "RuntimeRunStatus",
    "RuntimeExecutionError",
    "StrategyDecision",
    "StrategyExplanation",
    "StrategyRuntimeError",
    "StrategyRunner",
    "StrategyStateSnapshot",
    "canonical_sha256",
]
