"""Self-contained dashboard document for the local PTE operations console."""

DASHBOARD = r'''<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Paper Trading Engine</title>
<style>
:root{color-scheme:dark;--canvas:#080d14;--surface:#101721;--line:#263242;--line-soft:#1c2734;--text:#f2f5f8;--muted:#8997a8;--quiet:#59687a;--accent:#70a7ff;--accent-soft:#172b49;--good:#48c99a;--good-soft:#123329;--warn:#f2b84b;--warn-soft:#3a2b12;--bad:#ff777d;--bad-soft:#3a1b20;--radius:16px;--shadow:0 16px 48px rgba(0,0,0,.22)}
*{box-sizing:border-box}html{background:var(--canvas)}body{margin:0;min-height:100vh;background:linear-gradient(145deg,#0d1520 0,var(--canvas) 38%,#090f17 100%);color:var(--text);font:14px/1.5 Inter,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif;-webkit-font-smoothing:antialiased}button{font:inherit}.shell{width:min(1240px,100%);margin:0 auto;padding:28px 28px 60px}
.topbar{display:flex;align-items:flex-start;justify-content:space-between;gap:24px;margin-bottom:24px}.eyebrow{color:var(--accent);font-size:11px;font-weight:700;letter-spacing:.14em;text-transform:uppercase}.brand h1{margin:4px 0 3px;font-size:27px;line-height:1.2;letter-spacing:-.035em}.brand p{margin:0;color:var(--muted);font-size:13px}.status-area{display:flex;align-items:center;gap:10px}.sync{color:var(--quiet);font-size:12px;text-align:right}.pill{display:inline-flex;align-items:center;gap:7px;border:1px solid var(--line);border-radius:999px;background:rgba(16,23,33,.78);padding:7px 11px;color:var(--muted);font-size:12px;font-weight:650}.pill::before{content:"";width:7px;height:7px;border-radius:50%;background:var(--warn);box-shadow:0 0 0 4px rgba(242,184,75,.1)}
.controlbar{display:flex;align-items:center;justify-content:space-between;gap:18px;margin-bottom:16px;padding:14px 16px;border:1px solid var(--line);border-radius:var(--radius);background:rgba(16,23,33,.88);box-shadow:var(--shadow)}.control-copy strong{display:block;font-size:14px}.control-copy span{color:var(--muted);font-size:12px}.run-switch{display:inline-flex;align-items:center;gap:10px;min-width:178px;justify-content:center;border:1px solid #315b4b;border-radius:11px;background:var(--good-soft);color:#a5ead1;padding:10px 14px;cursor:pointer;font-weight:700;transition:transform .15s,border-color .15s,background .15s}.run-switch::before{content:"";width:9px;height:9px;border-radius:50%;background:var(--good);box-shadow:0 0 0 4px rgba(72,201,154,.13)}.run-switch[aria-checked="false"]{background:var(--warn-soft);border-color:#665027;color:#f4d38c}.run-switch[aria-checked="false"]::before{background:var(--warn);box-shadow:0 0 0 4px rgba(242,184,75,.13)}.run-switch:hover{transform:translateY(-1px)}.run-switch:disabled{opacity:.5;cursor:wait;transform:none}
.overview{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:12px}.metric-card,.panel{border:1px solid var(--line-soft);background:rgba(16,23,33,.9);border-radius:var(--radius)}.metric-card{min-height:112px;padding:17px 18px;position:relative;overflow:hidden}.metric-card::after{content:"";position:absolute;right:-24px;top:-28px;width:82px;height:82px;border-radius:50%;background:rgba(112,167,255,.035)}.label{color:var(--muted);font-size:12px}.metric-value{margin-top:13px;font-size:21px;line-height:1.15;font-weight:720;letter-spacing:-.025em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.metric-note{margin-top:5px;color:var(--quiet);font-size:11px}
.workspace{display:grid;grid-template-columns:minmax(0,5fr) minmax(0,7fr);gap:12px;margin-bottom:12px}.panel{padding:20px}.panel-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:17px}.panel-title{margin:0;font-size:14px;font-weight:700}.panel-kicker{color:var(--quiet);font-size:11px}.money{font-variant-numeric:tabular-nums}.account-primary .label{margin-bottom:5px}.account-primary strong{display:block;font-size:30px;letter-spacing:-.045em}.account-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:17px}.mini{border-top:1px solid var(--line);padding-top:12px}.mini strong{display:block;margin-top:3px;font-size:16px}
.decision-head{display:flex;align-items:center;gap:14px;margin-bottom:16px}.action-orb{display:grid;place-items:center;width:58px;height:58px;flex:0 0 auto;border-radius:15px;background:var(--accent-soft);color:#a8c9ff;font-size:16px;font-weight:800;border:1px solid #28466e}.action-orb[data-action="BUY"]{background:var(--good-soft);color:#91e4c5;border-color:#285643}.action-orb[data-action="SELL"]{background:var(--bad-soft);color:#ffabb0;border-color:#633038}.decision-meta strong{display:block;font-size:15px;margin-bottom:2px}.decision-meta span{color:var(--muted);font-size:12px}.facts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1px;background:var(--line-soft);border:1px solid var(--line-soft);border-radius:11px;overflow:hidden}.fact{min-width:0;background:var(--surface);padding:11px 12px}.fact strong{display:block;margin-top:3px;font-size:13px;font-weight:650;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.alert-banner{display:none;align-items:flex-start;gap:11px;margin-bottom:12px;padding:13px 15px;border:1px solid #604b22;border-radius:13px;background:rgba(58,43,18,.88);color:#f2d697}.alert-banner.show{display:flex}.alert-icon{display:grid;place-items:center;width:22px;height:22px;border-radius:50%;background:var(--warn);color:#241b0b;font-weight:900}.alert-content strong{display:block;font-size:13px}.alert-content div{color:#cbb98f;font-size:12px;margin-top:2px}
.lower{display:grid;grid-template-columns:minmax(0,8fr) minmax(260px,4fr);gap:12px}.table-panel{padding:0;overflow:hidden}.table-head{padding:18px 20px 14px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:680px}th,td{text-align:left;padding:11px 14px;border-top:1px solid var(--line-soft);font-variant-numeric:tabular-nums}th{color:var(--quiet);font-size:11px;font-weight:650;text-transform:uppercase;letter-spacing:.035em}td{font-size:12px}.empty{padding:32px!important;text-align:center;color:var(--quiet)}.danger{border:1px solid #633038;border-radius:8px;background:var(--bad-soft);color:#ffabb0;padding:6px 10px;cursor:pointer}.events{padding:0;overflow:hidden}.events-list{max-height:305px;overflow:auto;padding:0 18px 12px}.event{position:relative;padding:11px 0 11px 16px;border-top:1px solid var(--line-soft);color:#c7d0da;font-size:12px}.event::before{content:"";position:absolute;left:0;top:16px;width:6px;height:6px;border-radius:50%;background:var(--quiet)}.event time{display:block;color:var(--quiet);font-size:10px;margin-top:2px}
.diagnostics{margin-top:12px;border:1px solid var(--line-soft);border-radius:13px;background:rgba(16,23,33,.65);overflow:hidden}.diagnostics summary{padding:12px 16px;color:var(--muted);cursor:pointer;font-size:12px}.diagnostic-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:1px;border-top:1px solid var(--line-soft);background:var(--line-soft)}.diagnostic-item{min-width:0;background:var(--surface);padding:10px 14px}.diagnostic-item span{display:block;color:var(--quiet);font-size:10px}.diagnostic-item strong{display:block;margin-top:3px;color:#a9b9c9;font:11px/1.5 "Cascadia Code",Consolas,monospace;overflow-wrap:anywhere}.toast{position:fixed;right:20px;bottom:20px;z-index:10;max-width:380px;padding:12px 15px;border:1px solid #315b4b;border-radius:11px;background:#15372d;color:#b4ead6;box-shadow:var(--shadow);opacity:0;transform:translateY(12px);transition:.2s;pointer-events:none}.toast.show{opacity:1;transform:none}.toast.error{border-color:#633038;background:#3a1b20;color:#ffb5ba}
.virtual-section{margin-top:12px}.virtual-section>.panel-head{margin-bottom:12px}.virtual-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:12px}.virtual-card{padding:17px}.virtual-card h3{margin:0 0 8px}.virtual-card dl{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin:0}.virtual-card dt{color:var(--muted);font-size:11px}.virtual-card dd{margin:0;font-variant-numeric:tabular-nums}.virtual-card button{margin-top:12px;border:1px solid var(--line);border-radius:8px;background:var(--accent-soft);color:#a8c9ff;padding:7px 10px;cursor:pointer}.virtual-card button:disabled{opacity:.5;cursor:wait}
@media(max-width:820px){.shell{padding:22px 18px 50px}.overview{grid-template-columns:repeat(2,minmax(0,1fr))}.workspace,.lower{grid-template-columns:1fr}.facts{grid-template-columns:repeat(3,minmax(0,1fr))}.events-list{max-height:260px}}
@media(max-width:520px){.shell{padding:18px 14px 42px}.topbar{display:block}.status-area{margin-top:14px;justify-content:space-between}.sync{text-align:left}.brand h1{font-size:24px}.controlbar{align-items:flex-start;flex-direction:column}.run-switch{width:100%}.metric-card{min-height:96px;padding:15px}.metric-value{font-size:18px}.panel{padding:17px}.facts{grid-template-columns:repeat(2,minmax(0,1fr))}.account-primary strong{font-size:27px}.toast{left:14px;right:14px;bottom:14px}}
</style></head><body><div class="shell">
<header class="topbar"><div class="brand"><div class="eyebrow">Paper Trading Engine</div><h1>模拟交易控制台</h1><p>策略执行、账户状态与风险干预</p></div><div class="status-area"><div class="sync"><span>最近同步</span><br><strong id="lastUpdated">正在连接</strong></div><span class="pill" id="health">连接中</span></div></header>
<section class="controlbar" aria-label="PTE 运行控制"><div class="control-copy"><strong>自动交易引擎</strong><span>暂停仅阻止新订单，已有订单仍持续对账</span></div><button class="run-switch" id="runSwitch" role="switch" aria-checked="false" onclick="toggleRun()">正在读取状态</button></section>
<main><section class="overview" aria-label="运行概览">
<article class="metric-card"><div class="label">交易环境</div><div class="metric-value" id="environment">—</div><div class="metric-note">模拟账户</div></article><article class="metric-card"><div class="label">交易标的</div><div class="metric-value" id="symbol">—</div><div class="metric-note">当前策略标的</div></article><article class="metric-card"><div class="label">实际持仓</div><div class="metric-value" id="position">—</div><div class="metric-note">以成交回报为准</div></article><article class="metric-card"><div class="label">运行状态</div><div class="metric-value" id="runState">—</div><div class="metric-note">订单持续对账</div></article>
</section><div class="alert-banner" id="alertBanner" role="status"><span class="alert-icon">!</span><div class="alert-content"><strong>运行告警</strong><div id="alerts">暂无告警</div></div></div>
<section class="workspace"><article class="panel" aria-label="账户概览"><div class="panel-head"><h2 class="panel-title">账户概览</h2><span class="panel-kicker">SIMULATE</span></div><div class="account-primary"><div class="label">可用现金</div><strong class="money" id="cash">—</strong></div><div class="account-grid"><div class="mini"><span class="label">总资产</span><strong class="money" id="assets">—</strong></div><div class="mini"><span class="label">冻结资金</span><strong class="money" id="frozen">—</strong></div></div></article>
<article class="panel" aria-label="策略决策"><div class="panel-head"><h2 class="panel-title">最新策略决策</h2><span class="panel-kicker" id="decisionId">—</span></div><div class="decision-head"><div class="action-orb" id="decisionAction" data-action="WAIT">等待</div><div class="decision-meta"><strong id="decisionTitle">等待下一次策略信号</strong><span>有效交易日 <b id="validSession">—</b></span></div></div><div class="facts"><div class="fact"><span class="label">信号日期</span><strong id="signalDate">—</strong></div><div class="fact"><span class="label">目标持仓</span><strong id="target">—</strong></div><div class="fact"><span class="label">执行参考价</span><strong id="referencePrice">—</strong></div><div class="fact"><span class="label">可部署现金</span><strong id="deployableCash">—</strong></div><div class="fact"><span class="label">预计订单成本</span><strong id="estimatedCost">—</strong></div><div class="fact"><span class="label">预计剩余现金</span><strong id="remainingCash">—</strong></div><div class="fact"><span class="label">执行费率</span><strong id="feeRate">—</strong></div><div class="fact"><span class="label">策略动作</span><strong id="action">—</strong></div></div></article></section>
<section class="lower"><article class="panel table-panel"><div class="table-head"><h2 class="panel-title">订单</h2></div><div class="table-wrap"><table><thead><tr><th>订单号</th><th>方向</th><th>数量</th><th>限价</th><th>状态</th><th>累计成交</th><th>操作</th></tr></thead><tbody id="orderRows"></tbody></table></div></article><article class="panel events" aria-label="最近事件"><div class="table-head"><h2 class="panel-title">最近事件</h2></div><div class="events-list" id="events">暂无事件</div></article></section>
<section class="panel virtual-section" aria-label="虚拟账户"><div class="panel-head"><h2 class="panel-title">策略虚拟账户</h2><span class="panel-kicker" id="comparisonRange">尚无共同观察期</span></div><div class="virtual-grid" id="virtualAccounts"></div></section>
<details class="diagnostics" id="rawDetails"><summary>展开结构化诊断</summary><div class="diagnostic-list" id="diagnostics"></div></details></main></div><div class="toast" id="toast" aria-live="polite"></div>
<script>
const labels={SIMULATE:'模拟交易',CN:'中国市场',OK:'行情正常',DEGRADED_QUOTE:'行情降级',UNKNOWN:'状态未知',WAIT:'等待',HOLD:'持有',BUY:'买入',SELL:'卖出',PENDING:'等待成交',TOUCH_UNCERTAIN:'触价未穿价',UNFILLED:'当日未成交',FILLED:'已成交',SUBMITTING:'提交中',SUBMITTED:'已提交',SUBMIT_FAILED:'提交失败',FILLED_PART:'部分成交',FILLED_ALL:'全部成交',CANCELLED_PART:'部分撤销',CANCELLED_ALL:'全部撤销',FAILED:'失败',DISABLED:'已禁用',DELETED:'已删除',FILL_CANCELLED:'成交已撤销',ACTIVE_ORDER_BLOCKS_SUBMISSION:'存在活动订单，暂不提交',DECISION_NOT_VALID_TODAY:'当前不是决策有效交易日',OUTSIDE_SUBMISSION_WINDOW:'当前不在自动发单时段',ORDER_INTENT_CREATED:'已创建订单意图',ORDER_INTENT_RECOVERED:'已恢复待提交订单意图',ORDER_SUBMITTED:'订单已提交',FILL_INCREMENT:'收到新增成交',PAUSED:'已暂停自动下单',RESUMED:'已恢复自动运行',CANCEL_TOKEN_ISSUED:'已发出撤单确认令牌',CANCEL_REQUESTED:'已提交撤单请求',DATA_PUBLISHED:'完整收盘数据已发布',DATA_PUBLICATION_FAILED:'完整收盘数据发布失败',SCHEDULER_OPERATION_FAILED:'运行任务失败',SCHEDULER_OPERATION_RECOVERED:'运行任务已恢复',CHANNEL_REFRESH_FAILED:'Futu渠道刷新失败',VIRTUAL_ACCOUNT_FAILED:'虚拟账户刷新失败'};
const cn=x=>labels[x]||x||'—',money=x=>x==null?'—':Number(x).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2}),qty=x=>x==null?'—':Number(x).toLocaleString('zh-CN'),pct=x=>x==null?'—':`${(Number(x)*100).toFixed(2)}%`,ratio=x=>x==null?'—':Number(x).toFixed(3),set=(id,value)=>document.getElementById(id).textContent=value;
const localTime=x=>{if(!x)return'—';const d=new Date(x);return Number.isNaN(d.valueOf())?x:d.toLocaleString('zh-CN',{hour12:false})};
async function api(path,options){const r=await fetch(path,options),x=await r.json();if(!r.ok)throw Error(x.error||'请求失败');return x}
function showToast(message,error=false){const el=document.getElementById('toast');el.textContent=message;el.className='toast show'+(error?' error':'');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.className='toast',3000)}
function renderAlerts(items){const banner=document.getElementById('alertBanner'),box=document.getElementById('alerts');banner.classList.toggle('show',!!items?.length);box.textContent=items?.length?items.map(cn).join(' · '):'暂无告警'}
function renderEvents(items){const box=document.getElementById('events');box.replaceChildren();if(!items?.length){box.textContent='暂无事件';return}items.slice(0,12).forEach(e=>{const row=document.createElement('div');row.className='event';const text=document.createElement('span');text.textContent=cn(e.event_type);const time=document.createElement('time');time.textContent=localTime(e.created_at);row.append(text,time);box.appendChild(row)})}
function renderOrders(orders){const body=document.getElementById('orderRows');body.replaceChildren();if(!orders?.length){const row=body.insertRow(),cell=row.insertCell();cell.colSpan=7;cell.className='empty';cell.textContent='暂无订单';return}orders.forEach(o=>{const row=body.insertRow();[o.channel_order_id,cn(o.side),qty(o.quantity),money(o.limit_price),cn(o.status),qty(o.cumulative_filled_quantity)].forEach(v=>{const c=row.insertCell();c.textContent=v});const c=row.insertCell(),b=document.createElement('button');b.className='danger';b.textContent='撤单';b.onclick=()=>cancelOrder(o.channel_order_id);c.appendChild(b)})}
let lastState=null;
function renderVirtual(items){const box=document.getElementById('virtualAccounts');box.replaceChildren();if(!items.length){box.textContent='暂无虚拟账户';return}items.forEach(a=>{const m=a.metrics||{},card=document.createElement('article');card.className='metric-card virtual-card';const title=document.createElement('h3');title.textContent=a.name;const dl=document.createElement('dl');[['完整基线',a.baseline_version],['可用现金',money(a.cash)],['持仓',qty(a.quantity)],['最大回撤',pct(m.maximum_drawdown)],['卡玛比率',ratio(m.calmar_ratio)],['盈亏比',ratio(m.win_loss_ratio)],['累计收益',pct(m.total_return)],['运行状态',a.paused?'已暂停':'自动运行']].forEach(([k,v])=>{const d=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;d.append(dt,dd);dl.appendChild(d)});const b=document.createElement('button');b.textContent=a.paused?'恢复运行':'暂停新单';b.onclick=()=>toggleVirtual(a.account_id,!!a.paused,b);card.append(title,dl,b);box.appendChild(card)})}
function renderDiagnostics(payload){const box=document.getElementById('diagnostics');box.replaceChildren();const walk=(value,path='状态')=>{if(value&&typeof value==='object'){Object.entries(value).forEach(([k,v])=>walk(v,path+' / '+k));return}const item=document.createElement('div'),key=document.createElement('span'),val=document.createElement('strong');item.className='diagnostic-item';key.textContent=path;val.textContent=value==null?'—':String(value);item.append(key,val);box.appendChild(item)};walk(payload)}
function render(payload){lastState=payload;const s=payload.channel||payload,a=s.account||{},d=s.last_decision||{},action=d.action||'WAIT',comparison=payload.comparison||{};set('health',cn(s.quote_health));set('lastUpdated',new Date().toLocaleTimeString('zh-CN',{hour12:false}));set('environment',`${cn(s.environment)} / ${cn(s.market)}`);set('symbol',s.symbol);set('position',qty(s.actual_quantity));set('runState',s.paused?'已暂停':'自动运行');set('cash',money(a.cash));set('assets',money(a.total_assets));set('frozen',money(a.frozen_cash));set('decisionId',d.decision_id);set('signalDate',d.signal_date);set('validSession',d.valid_session);set('action',cn(action));set('target',qty(d.target_quantity));set('referencePrice',money(d.execution_reference_price));set('deployableCash',money(d.available_cash));set('feeRate',d.fee_rate==null?'—':`${(Number(d.fee_rate)*100).toFixed(4)}%`);set('estimatedCost',money(d.estimated_order_cost));set('remainingCash',money(d.unallocated_cash));set('comparisonRange',comparison.common_start?`共同观察期 ${comparison.common_start} 至 ${comparison.common_end}`:'尚无共同观察期');const orb=document.getElementById('decisionAction');orb.textContent=cn(action);orb.dataset.action=action;set('decisionTitle',action==='BUY'?'策略要求建立仓位':action==='SELL'?'策略要求退出仓位':action==='HOLD'?'保持当前持仓':'等待下一次策略信号');renderOrders(s.orders);renderAlerts(s.alerts);renderEvents(s.events);renderVirtual(payload.virtual_accounts||[]);renderDiagnostics(payload);const sw=document.getElementById('runSwitch');sw.setAttribute('aria-checked',String(!s.paused));sw.textContent=s.paused?'已暂停 · 点击恢复':'自动运行 · 点击暂停';sw.disabled=false}
async function refresh(){try{render(await api('/api/status'))}catch(e){showToast(`状态刷新失败：${e.message}`,true)}}
async function toggleRun(){if(!lastState)return;const sw=document.getElementById('runSwitch'),state=lastState.channel||lastState,paused=!!state.paused,path=paused?'/api/resume':'/api/pause',success=paused?'恢复成功':'暂停成功';sw.disabled=true;try{await api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await refresh();showToast(success)}catch(e){showToast(`操作失败：${e.message}`,true);await refresh()}finally{sw.disabled=false}}
async function toggleVirtual(id,paused,button){button.disabled=true;try{await api(`/api/virtual-accounts/${encodeURIComponent(id)}/${paused?'resume':'pause'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await refresh();showToast(paused?'虚拟账户已恢复':'虚拟账户已暂停')}catch(e){showToast(`虚拟账户操作失败：${e.message}`,true);button.disabled=false}}
async function cancelOrder(id){if(!confirm(`确认准备撤销订单 ${id}？`))return;try{const x=await api('/api/cancel-token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel_order_id:id})});if(confirm(`再次确认撤销订单 ${id}`)){const state=await api('/api/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel_order_id:id,token:x.token})});render(state);showToast('撤单请求已提交')}}catch(e){showToast(`撤单失败：${e.message}`,true)}}
refresh();setInterval(refresh,5000);
</script></body></html>'''
